spring:
  application:
    name: item-service
  rabbitmq:
    host: 176.212.33.21
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1
 
 
  cloud:
    inetutils:
      ignored-interfaces:
      - VM.*
      #preferred-networks:
      #- 176.212.33.15
#server:
  #port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: WuXian:${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
